# tomcat properties
server:
  context-path: /mhf
spring:
  redis:
    host: 101.132.108.40
    password: Teamw0rk
  mail:
    host: smtp.qq.com
    port: 587
    username: 295322187@qq.com
    password: fafbfuedshofbjbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true